version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend/presenter
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend

  # Backend services
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_HOST=rabbitmq
      - user=${user}
      - password=${password}
      - host=${host}
      - port=${port}
      - dbname=${dbname}
    env_file:
      - .env
    depends_on:
      - rabbitmq

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # PostgreSQL database
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=add_project
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data: 